name = "DistilBERT"
uuid = "4a3a1c16-5378-477a-8c70-c7b46c0a0f4d"
version = "0.1.0"
authors = ["AbrJA <abraham.jaimes.mx@gmail.com>"]

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Pickle = "fbb45041-c46e-462f-888f-7c521cafbc2c"
SafeTensors = "eeda0dda-7046-4914-a807-2495fc7abb89"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Flux = "^0.14, 0.16"
JSON = "^1"
NNlib = "^0.9"
Pickle = "^0.3"
SafeTensors = "^1"
julia = "^1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
